namespace: dseeley

name: esxifree_guest

version: AUTOFILLED_BY_JENKINS

readme: README.md

authors:
- Dougal Seeley <github@dougalseeley.com>

description: These Ansible modules get the info from, or create (or clone), ESXi virtual machines. They use direct SOAP calls and Paramiko SSH, to allow usage on the free hypervisor.

#license:
#- BSD-3-Clause

license_file: 'LICENSE'

tags: ['aws', 'gcp', 'azure', 'storage', 'cluster', 'cloud', 'system']

dependencies: {}

repository: https://github.com/dseeley/esxifree_guest

documentation: https://github.com/dseeley/esxifree_guest/blob/master/README.md

homepage: https://github.com/dseeley/esxifree_guest

issues: https://github.com/dseeley/esxifree_guest/issues

build_ignore: [ '.idea', 'jenkinsfiles', '.gitignore', 'Dockerfile*' ]

